"""Small, dependency-free config-entry compatibility helpers."""

from __future__ import annotations

from .const import ENTRY_TITLE


def migrated_entry_title(current_title: str, link_name: str | None) -> str:
    """Remove only the exact share name suffix generated by v2.0.0."""
    if link_name and current_title == f"{ENTRY_TITLE} ({link_name})":
        return ENTRY_TITLE
    return current_title
